name: Package

on:
  workflow_dispatch:

jobs:
  vllm-cpu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Checkout VLLM source
        uses: actions/checkout@v4
        with:
          repository: vllm-project/vllm

      - name: Install Poetry
        run: pipx install poetry

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: "poetry"

      - name: Install the project dependencies
        run: poetry install

      - name: Run setup script
        run: sh setup.sh

      - name: Check files
        run: ls -l
