name: Release

on:
  workflow_dispatch:

jobs:
  vllm-cpu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout vLLM source
        uses: actions/checkout@v4
        with:
          repository: vllm-project/vllm

      - name: Checkout build script
        uses: actions/checkout@v4
        with:
          path: scripts

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
          cache: "pip"

      - name: Build from source
        run: sh scripts/build.sh

      - name: Get vLLM version
        id: vllm
        run: echo "VERSION=$(grep -Eo '__version__\s*=\s*"[^"]+"' "source/vllm/version.py" | sed -E 's/__version__\s*=\s*"([^"]+)"/\1/')" > $GITHUB_OUTPUT

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.vllm.outputs.VERSION }}
          files: source/dist/*.egg
