name: Release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout vLLM source
        uses: actions/checkout@v4
        with:
          repository: vllm-project/vllm

      - name: Get vLLM version
        id: vllm
        run: echo "version=$(grep -Eo '__version__\s*=\s*"[^"]+"' "vllm/version.py" | sed -E 's/__version__\s*=\s*"([^"]+)"/\1/')" > $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          build-args: |
            - VLLM_CPU_DISABLE_AVX512="true"
          file: Dockerfile.cpu
          tags: ghcr.io/michaelhly/vllm:${{ steps.vllm.outputs.version }}-cpu
